# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lichsu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 361, 51))
        self.label_2.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0c3483, stop:0.5 #6b8cce, stop:1 #a2b6df);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.tieude_2 = QtWidgets.QLabel(self.centralwidget)
        self.tieude_2.setGeometry(QtCore.QRect(10, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tieude_2.setFont(font)
        self.tieude_2.setStyleSheet("color: white;")
        self.tieude_2.setObjectName("tieude_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 50, 361, 501))
        self.label.setStyleSheet("background-color: white;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.thoat_2 = QtWidgets.QPushButton(self.centralwidget)
        self.thoat_2.setGeometry(QtCore.QRect(280, 500, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.thoat_2.setFont(font)
        self.thoat_2.setStyleSheet("background-color: #94adda;\n"
"color: white;\n"
"")
        self.thoat_2.setObjectName("thoat_2")
        self.thoat_3 = QtWidgets.QPushButton(self.centralwidget)
        self.thoat_3.setGeometry(QtCore.QRect(170, 500, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.thoat_3.setFont(font)
        self.thoat_3.setStyleSheet("background-color: #94adda;\n"
"color: white;\n"
"")
        self.thoat_3.setObjectName("thoat_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tieude_2.setText(_translate("MainWindow", "Lịch sử dịch"))
        self.thoat_2.setText(_translate("MainWindow", "Quay lại"))
        self.thoat_3.setText(_translate("MainWindow", "Clear"))
